### ISSUE TITLE
Reload page on any changes to the views & src directory

### ISSUE THREAD

**Issue by mylastore** [jamg44/NodeTyped#11]
How can I live reload server on any changes to the views plus src directory?

**Comment by jamg44** [comment]
You don't need to reload the server when you make changes to the views, they are always used from the file system.

**Comment by mylastore** [comment]
Sorry I ment reload the browser automatically after a change has been made to any views.

**Comment by jamg44** [comment]
You can use some module like [livereload](https://www.npmjs.com/package/livereload) or [easy-livereload](https://github.com/dai-shi/easy-livereload)

**Comment by mylastore** [comment]
I will try that thanks.
